-- MySQL Script generated by MySQL Workbench
-- mar. 30 août 2022 10:55:40
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
SET
  @OLD_UNIQUE_CHECKS = @ @UNIQUE_CHECKS,
  UNIQUE_CHECKS = 0;

SET
  @OLD_FOREIGN_KEY_CHECKS = @ @FOREIGN_KEY_CHECKS,
  FOREIGN_KEY_CHECKS = 0;

SET
  @OLD_SQL_MODE = @ @SQL_MODE,
  SQL_MODE = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dataenigme
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dataenigme
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dataenigme`;

USE `dataenigme`;

-- -----------------------------------------------------
-- Table `dataenigme`.`membres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dataenigme`.`membres` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `isVerified` TINYINT NOT NULL,
  `isAdmin` TINYINT NOT NULL,
  `isBan` TINYINT NOT NULL,
  `avatar` VARCHAR(150) NOT NULL,
  `bio` VARCHAR(300) NULL,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `dataenigme`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dataenigme`.`message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `message` VARCHAR(200) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `sujet` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`message` ASC) VISIBLE
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `dataenigme`.`enigme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dataenigme`.`enigme` (
  `id_enigme` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(45) NOT NULL,
  `difficulty` INT NOT NULL,
  `content` TEXT NOT NULL,
  `solus` TEXT NOT NULL,
  `is_Verified` TINYINT NOT NULL DEFAULT 0,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_enigme`),
  INDEX `fk_Enigme_1_idx` (`id_user` ASC) VISIBLE,
  UNIQUE INDEX `id_enigme_UNIQUE` (`id_enigme` ASC) VISIBLE,
  CONSTRAINT `fk_Enigme_1` FOREIGN KEY (`id_user`) REFERENCES `dataenigme`.`membres` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `dataenigme`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dataenigme`.`images` (
  `name_image` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `path` VARCHAR(45) NOT NULL,
  `url` VARCHAR(150) NOT NULL,
  `id_enigme` INT NOT NULL,
  UNIQUE INDEX `id_enigme_UNIQUE` (`id_enigme` ASC),
  CONSTRAINT `fk_images_1` FOREIGN KEY (`id_enigme`) REFERENCES `dataenigme`.`enigme` (`id_enigme`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `dataenigme`.`timestamps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dataenigme`.`timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL DEFAULT NULL
);

-- -----------------------------------------------------
-- Table `dataenigme`.`enigme_reponse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dataenigme`.`enigme_reponse` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_enigme` INT NOT NULL,
  `id_user` INT NOT NULL,
  `id_solus` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `index2` (`id` ASC) VISIBLE,
  INDEX `fk_enigme_reponse_1_idx` (`id_enigme` ASC) VISIBLE,
  CONSTRAINT `fk_enigme_reponse_1` FOREIGN KEY (`id_enigme`) REFERENCES `dataenigme`.`enigme` (`id_enigme`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;

SET
  SQL_MODE = @OLD_SQL_MODE;

SET
  FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;

SET
  UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;

INSERT INTO
  `membres` (
    `id`,
    `name`,
    `password`,
    `email`,
    `isVerified`,
    `isAdmin`,
    `isBan`,
    `avatar`
  )
VALUES
  (
    1,
    'Admin',
    '$2b$10$3xZYGlHNX0XSn/D28.9e.Od608tlJ3ip2W2SqWKQEzrZJfwJ5i56e',
    'ludolpr@gmail.com',
    1,
    1,
    0,
    'default.png'
  );

INSERT INTO
  `message` (`message`, `name`, `sujet`, `email`)
VALUES
  (
    'test Admin',
    'Admin',
    'test',
    'ludolpr@gmail.com'
  );

INSERT INTO
  `enigme` (
    `titre`,
    `difficulty`,
    `content`,
    `solus`,
    `id_user`,
    `is_Verified`
  )
VALUES
  (
    "Inversé",
    4,
    "Pour moi, l'accouchement vient avant la grossesse, l'enfance avant la naissance, l'adolescence avant l'enfance, la mort avant la vie.",
    'le dictionnaire',
    1,
    1
  ),
  (
    "Le mot",
    4,
    "Quel mot commence par la lettre 'e' et contient une lettre ?",
    'Une enveloppe',
    1,
    1
  ),
  (
    "L'école",
    4,
    "Quel mot est représenté par ce nombre : 713705 ?",
    'Soleil',
    1,
    1
  ),
  (
    "L'inconnu",
    4,
    "Sans voix, je hurle
Sans ailes, je voltige
Sans dents, je mords
Sans bouche, je murmure

Qui suis-je ?",
    'Le vent',
    1,
    1
  ),
  (
    "La longue marche",
    4,
    "A ciel dégagé, on peut marcher vers lui mais jamais on ne l'atteint.

Qui est-ce ?",
    'Le soleil',
    1,
    1
  ),
  (
    "Le message",
    5,
    "Message colporté dans un but malveillant, Je suis aussi un sanglier de 2 à 3 ans. Je suis...",
    'Un ragot',
    1,
    1
  ),
  (
    " Autrefois",
    5,
    "Autrefois bien utile pour faire chauffer un lit, ce n'est pas toujours lui que l'on voit dans son habit. Je suis...",
    'Un moine',
    1,
    1
  ),
  (
    " Mûr",
    5,
    "Mûr à point, il est fauché; fauché on l'est de n'en avoir point. Je suis...",
    'Du blé',
    1,
    1
  ),
  (
    "Le pont",
    5,
    "C'est la partie intégrante d'un pont. Le rendre, c'est en avoir ras-le-bol. Et bien qu'il déserte nos écoles, contre les taches, c'est une protection. Je suis...

",
    'Un tablier',
    1,
    1
  ),
  (
    " La machine",
    5,
    "Redoutable machine de guerre, des portes lui cédèrent naguère. Généralement il blatère, et c'est aussi un signe de feu. Je suis...",
    'Un bélier',
    1,
    1
  )