-- MySQL Script generated by MySQL Workbench
-- jeu. 21 juil. 2022 15:24:11
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dataenigme
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dataenigme
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dataenigme` ;
USE `dataenigme` ;

-- -----------------------------------------------------
-- Table `dataenigme`.`enigme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dataenigme`.`enigme` (
  `id_enigme` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(45) NOT NULL,
  `content` TEXT NOT NULL,
  `solus` TEXT NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_enigme`),
  INDEX `fk_Enigme_1_idx` (`id_user` ASC) VISIBLE,
  UNIQUE INDEX `id_enigme_UNIQUE` (`id_enigme` ASC) VISIBLE,
  CONSTRAINT `fk_Enigme_1`
    FOREIGN KEY (`id_user`)
    REFERENCES `dataenigme`.`membres` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dataenigme`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dataenigme`.`images` (
  `id_image` INT NOT NULL AUTO_INCREMENT,
  `name_image` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `path` VARCHAR(45) NOT NULL,
  `url` VARCHAR(150) NOT NULL,
  `id_enigme` INT NOT NULL,
  PRIMARY KEY (`id_image`),
  INDEX `fk_images_1_idx` (`id_enigme` ASC) VISIBLE,
  UNIQUE INDEX `id_enigme_UNIQUE` (`id_enigme` ASC) VISIBLE,
  UNIQUE INDEX `id_image_UNIQUE` (`id_image` ASC) VISIBLE,
  CONSTRAINT `fk_images_1`
    FOREIGN KEY (`id_enigme`)
    REFERENCES `dataenigme`.`enigme` (`id_enigme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dataenigme`.`membres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dataenigme`.`membres` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `avatar` INT NOT NULL,
  `isVerified` TINYINT NOT NULL,
  `isAdmin` TINYINT NOT NULL,
  `isBan` TINYINT NOT NULL,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_membres_1_idx` (`avatar` ASC) VISIBLE,
  CONSTRAINT `fk_membres_1`
    FOREIGN KEY (`avatar`)
    REFERENCES `dataenigme`.`images` (`id_image`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dataenigme`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dataenigme`.`message` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `message` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `sujet` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`message` ASC) VISIBLE,
  INDEX `fk_message_1_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_message_1`
    FOREIGN KEY (`id_user`)
    REFERENCES `dataenigme`.`membres` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `add`.`coloumn` 
-- -----------------------------------------------------
ALTER TABLE `articles` ADD `COLUMN ville` VARCHAR (255);

ALTER TABLE `perso` ADD `nom` VARCHAR (255) ADD `prenom` VARCHAR (255);

-- -----------------------------------------------------
-- Table `perso` & jeter`coloumn` 
-- -----------------------------------------------------
ALTER TABLE perso AND DROP nom;


-- -----------------------------------------------------
-- Table `dataenigme`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dataenigme`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


-- -----------------------------------------------------
-- Table `dataenigme`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dataenigme`.`category` (
  `category_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`category_id`));


-- -----------------------------------------------------
-- Table `dataenigme`.`timestamps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dataenigme`.`timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);


-- -----------------------------------------------------
-- Table `dataenigme`.`enigme_reponse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dataenigme`.`enigme_reponse` (
  `id` INT NOT NULL,
  `id_enigme` INT NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `index2` (`id` ASC) VISIBLE,
  INDEX `fk_enigme_reponse_1_idx` (`id_enigme` ASC) VISIBLE,
  CONSTRAINT `fk_enigme_reponse_1`
    FOREIGN KEY (`id_enigme`)
    REFERENCES `dataenigme`.`enigme` (`id_enigme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
